/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during development/builds.
// Keeping it here lets typecheck pass before the first Next command runs.
